# Generated by Django 4.0.1 on 2022-01-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], help_text='Gender of the user', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(default='[]', help_text='Skill set of the user', max_length=1000),
        ),
    ]
