# Generated by Django 4.0.1 on 2022-01-09 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(help_text="Code of the problem's solution by the user", null=True),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='given_constraint',
            field=models.TextField(help_text='Constraint for the problem', max_length=500),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.TextField(help_text="Code of the problem's solution"),
        ),
        migrations.AlterField(
            model_name='solution',
            name='complexity_analysis',
            field=models.TextField(help_text='Complexity analysis of the solution', max_length=1000),
        ),
        migrations.AlterField(
            model_name='solution',
            name='explaination',
            field=models.TextField(help_text='Explaintion of the solution', max_length=1000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='explaination',
            field=models.TextField(blank=True, help_text='Explaintion of the testcase', max_length=500),
        ),
    ]
